// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "wizard":return img`
................................
................................
.............aaaaaa.............
.............aaaaaa.............
............aaaaaaaa............
............aaaaaaaa............
..........aaaaaffaaaaa..........
..........aaaffffffaaa..........
..........aaaffffffaaa..........
........aaaaaffffffaaaaa........
........aaaaffffffffaaaa........
........aaaaffffffffaaaa........
........aaaaffffffffaaaa........
.......aaaaaffffffffaaaaa.......
.......aaaaaffffffffaaaaa.......
.......aaaaaaffffffaaaaaa.......
.......aaaaa5aaaaaa5aaaaa.......
.......aaaaa5aaaaaa5aaaaa.......
.....aaaaaaaa555555aaaaaaaa.....
.....aaaaaaaaaaaaaaaaaaaaaa.....
.....aaaaaaaaaaaaaaaaaaaaaa.....
.....aaaaaaaaaaaaaaaaaaaaaa.....
.....aaaaaaaaaaaaaaaaaaaaaa.....
.....aaaaaaaaaaaaaaaaaaaaaa.....
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
...aaaaaaaaaaaaaaaaaaaaaaaaaa...
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
